// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-VZPivjwtD8LB-4h5JiEY2e5bTOMA98I',
    appId: '1:1014236146041:android:418b10b0e0d7dd81ed67a8',
    messagingSenderId: '1014236146041',
    projectId: 'kipgo-taxi',
    databaseURL: 'https://kipgo-taxi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kipgo-taxi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKi2xX2aVN4WMie8xBOTY4LFty6ITwAqA',
    appId: '1:1014236146041:ios:eb2a362bbb6efd8ced67a8',
    messagingSenderId: '1014236146041',
    projectId: 'kipgo-taxi',
    databaseURL: 'https://kipgo-taxi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kipgo-taxi.firebasestorage.app',
    iosBundleId: 'com.kipgotaxi.app',
  );

}